### ISSUE TITLE
Error handling is terrible.

### ISSUE THREAD

**Issue by jessta** [mdlayher/goat#13]
Running errcheck(https://github.com/kisielk/errcheck) over this code highlights 47 ignored error return values.

In the places where errors are actually checked they are commonly just logged and then the program continues on blindly.

The database Save() methods ignore any errors from the database and just return true.

**Comment by mdlayher** [comment]
Thanks for your concern, and for providing a link to that tool.  I'm having a hard time getting it to compile and install (errors in one of its dependencies), so would you mind posting a gist with the output of the tool?

I consider the software to be in pre-release state, but admittedly, there were certain areas I rushed through in order to get a feature done. It is definitely in need of some further work.
